import { mix, alpha, lighten, darken, readable, contrast } from './color.mjs';

const alphaOf = alpha;
const mixOf = mix;

function tokens(s) {
  const dark = s.variant === 'dark';
  const up = (c, t) => (dark ? lighten(c, t) : darken(c, t));
  const dn = (c, t) => (dark ? darken(c, t) : lighten(c, t));

  const bg = s.bg;
  const elev = s.bgElev || up(bg, 0.05);
  const chrome = s.bgChrome || dn(bg, 0.3);
  const over = s.bgOverlay || up(bg, 0.1);
  const fg = s.fg;
  const dim = readable(s.fgDim || mix(fg, bg, 0.32), bg, 5.2);
  const faint = readable(s.fgFaint || mix(fg, bg, 0.58), bg, 3.2);
  const ghost = readable(mix(fg, bg, 0.68), bg, 2.6);
  const line = mix(bg, fg, 0.13);
  const line2 = mix(bg, fg, 0.24);
  const acc = s.accent || s.syntax.keyword;
  const sel = alpha(acc, dark ? 0.3 : 0.24);
  const selSoft = alpha(acc, dark ? 0.16 : 0.13);
  const onColor = (c) => {
    const white = contrast('#ffffff', c);
    const ink = contrast('#101014', c);
    if (white >= 4.5) return '#ffffff';
    if (ink >= 4.5) return '#101014';
    return white > ink ? '#ffffff' : '#101014';
  };
  const onAcc = onColor(acc);
  const st = s.status;
  const shadowInk = dark ? '#000000' : '#1a1a2e';
  const sh = (k) => alpha(shadowInk, dark ? k : k * 0.45);
  const shadow = sh(0.28);

  const y = s.syntax;
  return { bg, elev, chrome, over, fg, dim, faint, ghost, line, line2, acc, sel, selSoft, onAcc, onColor, st, y, ansi: s.ansi, shadow, sh, up, dn, dark, editor: {
    foreground: fg,
    descriptionForeground: dim,
    disabledForeground: faint,
    errorForeground: st.error,
    focusBorder: alpha(acc, 0.6),
    'icon.foreground': dim,
    'selection.background': sel,
    'widget.border': line2,
    'widget.shadow': sh(0.26),
    'sash.hoverBorder': acc,
    'toolbar.hoverBackground': alpha(fg, 0.06),
    'toolbar.activeBackground': alpha(fg, 0.10),
    'contrastBorder': '#00000000',
    'contrastActiveBorder': '#00000000',

    'textLink.foreground': y.func,
    'textLink.activeForeground': y.string,
    'textPreformat.foreground': readable(y.number, mix(chrome, y.number, 0.12), 5.4),
    'textPreformat.background': alpha(y.number, 0.10),
    'textBlockQuote.background': elev,
    'textBlockQuote.border': acc,
    'textCodeBlock.background': elev,
    'textSeparator.foreground': line2,

    'editor.background': bg,
    'editor.foreground': fg,
    'editorLineNumber.foreground': ghost,
    'editorLineNumber.activeForeground': acc,
    'editorLineNumber.dimmedForeground': mix(faint, bg, 0.55),
    'editorCursor.foreground': acc,
    'editorCursor.background': bg,
    'editorMultiCursor.primary.foreground': acc,
    'editorMultiCursor.secondary.foreground': mix(acc, bg, 0.4),
    'editor.selectionBackground': sel,
    'editor.selectionForeground': fg,
    'editor.inactiveSelectionBackground': selSoft,
    'editor.selectionHighlightBackground': selSoft,
    'editor.selectionHighlightBorder': '#00000000',
    'editor.wordHighlightBackground': alpha(y.func, 0.18),
    'editor.wordHighlightStrongBackground': alpha(y.type, 0.2),
    'editor.wordHighlightTextBackground': alpha(y.func, 0.14),
    'editor.findMatchBackground': alpha(y.number, 0.38),
    'editor.findMatchBorder': y.number,
    'editor.findMatchHighlightBackground': alpha(y.string, 0.24),
    'editor.findMatchForeground': fg,
    'editor.findMatchHighlightForeground': fg,
    'editor.findRangeHighlightBackground': alpha(acc, 0.1),
    'editor.hoverHighlightBackground': alpha(acc, 0.14),
    'editor.lineHighlightBackground': up(bg, dark ? 0.035 : 0.02),
    'editor.lineHighlightBorder': '#00000000',
    'editor.rangeHighlightBackground': alpha(acc, 0.1),
    'editor.symbolHighlightBackground': alpha(y.type, 0.2),
    'editor.foldBackground': alpha(acc, 0.08),
    'editor.foldPlaceholderForeground': faint,
    'editorLink.activeForeground': y.string,
    'editorWhitespace.foreground': mix(bg, fg, 0.2),
    'editorIndentGuide.background1': line,
    'editorIndentGuide.activeBackground1': mix(bg, fg, 0.34),
    'editorRuler.foreground': line,
    'editorCodeLens.foreground': mix(y.comment, fg, 0.15),
    'editorLightBulb.foreground': st.warn,
    'editorLightBulbAutoFix.foreground': st.ok,
    'editorLightBulbAi.foreground': y.tag,
    'editorBracketMatch.background': alpha(acc, 0.2),
    'editorBracketMatch.border': y.string,
    'editorBracketHighlight.foreground1': y.keyword,
    'editorBracketHighlight.foreground2': y.string,
    'editorBracketHighlight.foreground3': y.number,
    'editorBracketHighlight.foreground4': y.type,
    'editorBracketHighlight.foreground5': y.func,
    'editorBracketHighlight.foreground6': y.tag,
    'editorBracketHighlight.unexpectedBracket.foreground': st.error,
    'editorBracketPairGuide.background1': alpha(y.keyword, 0.28),
    'editorBracketPairGuide.background2': alpha(y.string, 0.28),
    'editorBracketPairGuide.background3': alpha(y.number, 0.28),
    'editorBracketPairGuide.activeBackground1': alpha(y.keyword, 0.6),
    'editorBracketPairGuide.activeBackground2': alpha(y.string, 0.6),
    'editorBracketPairGuide.activeBackground3': alpha(y.number, 0.6),

    'editorError.foreground': st.error,
    'editorWarning.foreground': st.warn,
    'editorInfo.foreground': st.info,
    'editorHint.foreground': st.ok,
    'editorError.background': alpha(st.error, 0.08),
    'editorWarning.background': alpha(st.warn, 0.08),
    'editorInfo.background': alpha(st.info, 0.08),
    'problemsErrorIcon.foreground': st.error,
    'problemsWarningIcon.foreground': st.warn,
    'problemsInfoIcon.foreground': st.info,

    'editorGutter.background': bg,
    'editorGutter.modifiedBackground': st.modified,
    'editorGutter.addedBackground': st.added,
    'editorGutter.deletedBackground': st.deleted,
    'editorGutter.commentRangeForeground': faint,
    'editorGutter.commentGlyphForeground': dim,
    'editorGutter.commentUnresolvedGlyphForeground': st.warn,
    'editorGutter.foldingControlForeground': dim,
    'editorGutter.itemBackground': alpha(acc, 0.14),
    'editorGutter.itemGlyphForeground': fg,

    'editorOverviewRuler.border': '#00000000',
    'editorOverviewRuler.background': bg,
    'editorOverviewRuler.findMatchForeground': alpha(y.number, 0.6),
    'editorOverviewRuler.rangeHighlightForeground': alpha(acc, 0.4),
    'editorOverviewRuler.selectionHighlightForeground': alpha(acc, 0.4),
    'editorOverviewRuler.wordHighlightForeground': alpha(y.func, 0.4),
    'editorOverviewRuler.wordHighlightStrongForeground': alpha(y.type, 0.4),
    'editorOverviewRuler.wordHighlightTextForeground': alpha(y.func, 0.3),
    'editorOverviewRuler.modifiedForeground': alpha(st.modified, 0.8),
    'editorOverviewRuler.addedForeground': alpha(st.added, 0.8),
    'editorOverviewRuler.deletedForeground': alpha(st.deleted, 0.8),
    'editorOverviewRuler.errorForeground': st.error,
    'editorOverviewRuler.warningForeground': st.warn,
    'editorOverviewRuler.infoForeground': st.info,
    'editorOverviewRuler.bracketMatchForeground': y.string,
    'editorOverviewRuler.inlineChatInserted': alpha(st.added, 0.5),
    'editorOverviewRuler.inlineChatRemoved': alpha(st.deleted, 0.5),

    'editorWidget.background': elev,
    'editorWidget.foreground': fg,
    'editorWidget.border': line2,
    'editorWidget.resizeBorder': acc,
    'editorHoverWidget.background': elev,
    'editorHoverWidget.foreground': fg,
    'editorHoverWidget.border': line2,
    'editorHoverWidget.highlightForeground': y.string,
    'editorHoverWidget.statusBarBackground': over,
    'editorSuggestWidget.background': elev,
    'editorSuggestWidget.border': line2,
    'editorSuggestWidget.foreground': fg,
    'editorSuggestWidget.highlightForeground': y.string,
    'editorSuggestWidget.focusHighlightForeground': y.string,
    'editorSuggestWidget.selectedBackground': over,
    'editorSuggestWidget.selectedForeground': fg,
    'editorSuggestWidget.selectedIconForeground': acc,
    'editorSuggestWidgetStatus.foreground': dim,
    'editorGhostText.foreground': readable(mix(y.comment, fg, 0.1), bg, 3.2),
    'editorGhostText.border': '#00000000',
    'editorGhostText.background': '#00000000',
    'editorStickyScroll.background': mix(bg, elev, 0.5),
    'editorStickyScroll.border': line,
    'editorStickyScroll.shadow': sh(0.10),
    'editorStickyScrollHover.background': over,
    'editorInlayHint.background': alpha(acc, 0.08),
    'editorInlayHint.foreground': readable(mix(fg, bg, 0.18), mix(bg, acc, 0.1), 5.0),
    'editorInlayHint.typeBackground': alpha(y.type, 0.08),
    'editorInlayHint.typeForeground': readable(mix(y.type, fg, 0.3), mix(bg, y.type, 0.1), 4.5),
    'editorInlayHint.parameterBackground': alpha(y.param, 0.08),
    'editorInlayHint.parameterForeground': readable(mix(y.param, fg, 0.3), mix(bg, y.param, 0.1), 4.5),
    'editorUnnecessaryCode.opacity': alpha('#000000', 0.55),
    'editorUnnecessaryCode.border': '#00000000',

    'editorActionList.background': elev,
    'editorActionList.foreground': fg,
    'editorActionList.focusBackground': over,
    'editorActionList.focusForeground': fg,
  } };
}

function chrome(t) {
  const { onColor, sh, bg, elev, chrome: ch, over, fg, dim, faint, line, line2, acc, sel, onAcc, st, y, shadow, up, dn, dark } = t;
  return {
    'titleBar.activeBackground': ch,
    'titleBar.activeForeground': readable(dim, ch, 4.5),
    'titleBar.inactiveBackground': ch,
    'titleBar.inactiveForeground': readable(faint, ch, 3.2),
    'titleBar.border': line,

    'commandCenter.background': alphaOf(fg, 0.05),
    'commandCenter.foreground': readable(dim, ch, 5.0),
    'commandCenter.border': line2,
    'commandCenter.activeBackground': alphaOf(fg, 0.1),
    'commandCenter.activeForeground': fg,
    'commandCenter.activeBorder': acc,
    'commandCenter.inactiveBorder': line,
    'commandCenter.debuggingBackground': alphaOf(acc, 0.2),

    'activityBar.background': ch,
    'activityBar.foreground': fg,
    'activityBar.inactiveForeground': readable(faint, ch, 3.2),
    'activityBar.border': line,
    'activityBar.activeBorder': acc,
    'activityBar.activeBackground': '#00000000',
    'activityBar.activeFocusBorder': acc,
    'activityBar.dropBorder': acc,
    'activityBarBadge.background': acc,
    'activityBarBadge.foreground': onAcc,
    'activityBarTop.background': ch,
    'activityBarTop.foreground': fg,
    'activityBarTop.inactiveForeground': faint,
    'activityBarTop.activeBorder': acc,
    'activityBarTop.activeBackground': over,
    'activityBarTop.dropBorder': acc,
    'modernActivityBar.activeBackground': bg,
    'modernActivityBar.activeForeground': fg,
    'modernActivityBar.hoverBackground': elev,
    'modernActivityBar.hoverForeground': fg,

    'profileBadge.background': acc,
    'profileBadge.foreground': onAcc,
    'profiles.sashBorder': line2,

    'sideBar.background': elev,
    'sideBar.foreground': readable(mixOf(fg, elev, 0.18), elev, 4.5),
    'sideBar.border': line,
    'sideBar.dropBackground': alphaOf(acc, 0.16),
    'sideBarTitle.background': elev,
    'sideBarTitle.foreground': readable(dim, elev, 4.5),
    'sideBarTitle.border': line,
    'sideBarSectionHeader.background': elev,
    'sideBarSectionHeader.foreground': fg,
    'sideBarSectionHeader.border': line,
    'sideBarActivityBarTop.border': line,
    'sideBarStickyScroll.background': elev,
    'sideBarStickyScroll.border': line,
    'sideBarStickyScroll.shadow': sh(0.18),

    'list.activeSelectionBackground': over,
    'list.activeSelectionForeground': fg,
    'list.activeSelectionIconForeground': acc,
    'list.inactiveSelectionBackground': alphaOf(fg, 0.06),
    'list.inactiveSelectionForeground': fg,
    'list.inactiveSelectionIconForeground': dim,
    'list.hoverBackground': alphaOf(fg, 0.06),
    'list.hoverForeground': fg,
    'list.focusBackground': over,
    'list.focusForeground': fg,
    'list.focusOutline': '#00000000',
    'list.focusAndSelectionOutline': '#00000000',
    'list.focusHighlightForeground': y.string,
    'list.inactiveFocusBackground': alphaOf(fg, 0.04),
    'list.inactiveFocusOutline': '#00000000',
    'list.highlightForeground': y.string,
    'list.errorForeground': st.error,
    'list.warningForeground': st.warn,
    'list.deemphasizedForeground': faint,
    'list.invalidItemForeground': st.error,
    'list.dropBackground': alphaOf(acc, 0.16),
    'list.dropBetweenBackground': acc,
    'list.filterMatchBackground': alphaOf(y.number, 0.3),
    'list.filterMatchBorder': y.number,
    'listFilterWidget.background': over,
    'listFilterWidget.outline': acc,
    'listFilterWidget.noMatchesOutline': st.error,
    'listFilterWidget.shadow': sh(0.22),
    'tree.indentGuidesStroke': line2,
    'tree.inactiveIndentGuidesStroke': line,
    'tree.tableColumnsBorder': line,
    'tree.tableOddRowsBackground': alphaOf(fg, 0.03),

    'editorGroup.border': line,
    'editorGroup.dropBackground': alphaOf(acc, 0.14),
    'editorGroup.emptyBackground': bg,
    'editorGroup.focusedEmptyBorder': acc,
    'editorGroup.dropIntoPromptBackground': elev,
    'editorGroup.dropIntoPromptForeground': fg,
    'editorGroup.dropIntoPromptBorder': line2,
    'editorGroupHeader.tabsBackground': ch,
    'editorGroupHeader.tabsBorder': line,
    'editorGroupHeader.noTabsBackground': ch,
    'editorGroupHeader.border': line,

    'tab.activeBackground': bg,
    'tab.activeForeground': fg,
    'tab.activeBorder': bg,
    'tab.activeBorderTop': acc,
    'tab.inactiveBackground': ch,
    'tab.inactiveForeground': mix(dim, faint, 0.4),
    'tab.border': line,
    'tab.hoverBackground': elev,
    'tab.hoverForeground': fg,
    'tab.hoverBorder': '#00000000',
    'tab.unfocusedActiveBackground': bg,
    'tab.unfocusedActiveForeground': dim,
    'tab.unfocusedActiveBorder': '#00000000',
    'tab.unfocusedActiveBorderTop': mixOf(acc, ch, 0.5),
    'tab.unfocusedInactiveBackground': ch,
    'tab.unfocusedInactiveForeground': faint,
    'tab.unfocusedHoverBackground': elev,
    'tab.unfocusedHoverForeground': dim,
    'tab.unfocusedHoverBorder': '#00000000',
    'tab.lastPinnedBorder': line2,
    'tab.dragAndDropBorder': acc,
    'tab.activeModifiedBorder': st.modified,
    'tab.inactiveModifiedBorder': mixOf(st.modified, ch, 0.5),
    'tab.unfocusedActiveModifiedBorder': mixOf(st.modified, ch, 0.4),
    'tab.unfocusedInactiveModifiedBorder': mixOf(st.modified, ch, 0.65),
    'tab.selectedBackground': bg,
    'tab.selectedForeground': fg,
    'tab.selectedBorderTop': acc,
    'modernTab.activeBackground': bg,
    'modernTab.activeForeground': fg,
    'modernTab.hoverBackground': elev,
    'modernTab.hoverForeground': fg,
    'modernEditorTab.activeBackground': bg,
    'modernEditorTab.activeForeground': fg,
    'modernEditorTab.inactiveBackground': '#00000000',
    'modernEditorTab.hoverBackground': elev,
    'modernEditorTab.hoverForeground': fg,
    'modernEditorTab.activeHoverBackground': elev,
    'modernEditorTab.activeActionBackground': bg,
    'modernEditorTab.activeHoverActionBackground': elev,
    'modernEditorTab.hoverActionBackground': elev,
    'modernEditorTab.selectedActionBackground': bg,

    'breadcrumb.background': bg,
    'breadcrumb.foreground': dim,
    'breadcrumb.focusForeground': fg,
    'breadcrumb.activeSelectionForeground': y.string,
    'breadcrumbPicker.background': elev,

    'panel.background': elev,
    'panel.border': line,
    'panel.dropBorder': acc,
    'panelTitle.activeBorder': acc,
    'panelTitle.activeForeground': fg,
    'panelTitle.inactiveForeground': readable(faint, elev, 3.2),
    'panelTitle.border': line,
    'panelInput.border': line2,
    'panelSection.border': line,
    'panelSection.dropBackground': alphaOf(acc, 0.14),
    'panelSectionHeader.background': elev,
    'panelSectionHeader.foreground': fg,
    'panelSectionHeader.border': line,
    'panelStickyScroll.background': elev,
    'panelStickyScroll.border': line,
    'panelStickyScroll.shadow': sh(0.18),
    'outputView.background': elev,

    'statusBar.background': ch,
    'statusBar.foreground': readable(dim, ch, 4.5),
    'statusBar.border': line,
    'statusBar.debuggingBackground': st.warn,
    'statusBar.debuggingForeground': onColor(st.warn),
    'statusBar.debuggingBorder': '#00000000',
    'statusBar.noFolderBackground': ch,
    'statusBar.noFolderForeground': readable(faint, ch, 3.2),
    'statusBar.noFolderBorder': line,
    'statusBar.focusBorder': acc,
    'statusBarItem.hoverBackground': alphaOf(fg, 0.1),
    'statusBarItem.hoverForeground': fg,
    'statusBarItem.activeBackground': alphaOf(fg, 0.16),
    'statusBarItem.focusBorder': acc,
    'statusBarItem.prominentBackground': alphaOf(fg, 0.14),
    'statusBarItem.prominentForeground': fg,
    'statusBarItem.prominentHoverBackground': alphaOf(fg, 0.2),
    'statusBarItem.prominentHoverForeground': fg,
    'statusBarItem.remoteBackground': acc,
    'statusBarItem.remoteForeground': onAcc,
    'statusBarItem.remoteHoverBackground': up(acc, 0.12),
    'statusBarItem.remoteHoverForeground': onAcc,
    'statusBarItem.errorBackground': st.error,
    'statusBarItem.errorForeground': onColor(st.error),
    'statusBarItem.errorHoverBackground': up(st.error, 0.1),
    'statusBarItem.errorHoverForeground': onColor(up(st.error, 0.1)),
    'statusBarItem.warningBackground': st.warn,
    'statusBarItem.warningForeground': onColor(st.warn),
    'statusBarItem.warningHoverBackground': up(st.warn, 0.1),
    'statusBarItem.warningHoverForeground': onColor(up(st.warn, 0.1)),
    'statusBarItem.compactHoverBackground': alphaOf(fg, 0.14),
    'statusBarItem.offlineBackground': st.deleted,
    'statusBarItem.offlineForeground': onColor(st.deleted),
    'statusBarItem.offlineHoverBackground': up(st.deleted, 0.1),
    'statusBarItem.offlineHoverForeground': onColor(up(st.deleted, 0.1)),
  };
}

function controls(t) {
  const { onColor, sh, bg, elev, chrome: ch, over, fg, dim, faint, line, line2, acc, onAcc, st, y, shadow, up, dn, dark } = t;
  const field = dark ? mixOf(bg, fg, 0.08) : '#ffffff';
  return {
    'input.background': field,
    'input.foreground': fg,
    'input.border': line2,
    'input.placeholderForeground': readable(faint, field, 3.2),
    'inputOption.activeBackground': alphaOf(acc, 0.22),
    'inputOption.activeBorder': acc,
    'inputOption.activeForeground': fg,
    'inputOption.hoverBackground': alphaOf(fg, 0.1),
    'inputValidation.errorBackground': mixOf(bg, st.error, dark ? 0.12 : 0.03),
    'inputValidation.errorForeground': fg,
    'inputValidation.errorBorder': st.error,
    'inputValidation.warningBackground': mixOf(bg, st.warn, dark ? 0.14 : 0.07),
    'inputValidation.warningForeground': fg,
    'inputValidation.warningBorder': st.warn,
    'inputValidation.infoBackground': mixOf(bg, st.info, dark ? 0.14 : 0.07),
    'inputValidation.infoForeground': fg,
    'inputValidation.infoBorder': st.info,

    'dropdown.background': field,
    'dropdown.listBackground': elev,
    'dropdown.foreground': fg,
    'dropdown.border': line2,

    'button.background': acc,
    'button.foreground': onAcc,
    'button.border': '#00000000',
    'button.hoverBackground': up(acc, 0.12),
    'button.separator': alphaOf(onAcc, 0.35),
    'button.secondaryBackground': over,
    'button.secondaryForeground': fg,
    'button.secondaryHoverBackground': mixOf(over, fg, 0.08),
    'extensionButton.background': acc,
    'extensionButton.foreground': onAcc,
    'extensionButton.border': '#00000000',
    'extensionButton.hoverBackground': up(acc, 0.12),
    'extensionButton.prominentBackground': acc,
    'extensionButton.prominentForeground': onAcc,
    'extensionButton.prominentHoverBackground': up(acc, 0.12),
    'extensionButton.separator': alphaOf(onAcc, 0.35),
    'extensionBadge.remoteBackground': acc,
    'extensionBadge.remoteForeground': onAcc,
    'extensionIcon.starForeground': st.warn,
    'extensionIcon.verifiedForeground': st.ok,
    'extensionIcon.preReleaseForeground': y.tag,
    'extensionIcon.sponsorForeground': y.tag,

    'checkbox.background': field,
    'checkbox.foreground': readable(acc, field, 5.0),
    'checkbox.border': line2,
    'checkbox.selectBackground': elev,
    'checkbox.selectBorder': acc,
    'radio.activeBackground': alphaOf(acc, 0.2),
    'radio.activeForeground': fg,
    'radio.activeBorder': acc,
    'radio.inactiveBackground': alphaOf(fg, 0.04),
    'radio.inactiveForeground': dim,
    'radio.inactiveBorder': line2,
    'radio.inactiveHoverBackground': alphaOf(fg, 0.08),

    'badge.background': acc,
    'badge.foreground': onAcc,
    'progressBar.background': acc,
    'gauge.background': alphaOf(acc, 0.25),
    'gauge.foreground': acc,
    'gauge.border': line2,
    'gauge.warningBackground': alphaOf(st.warn, 0.25),
    'gauge.warningForeground': st.warn,
    'gauge.errorBackground': alphaOf(st.error, 0.25),
    'gauge.errorForeground': st.error,

    'scrollbar.shadow': '#00000000',
    'scrollbarSlider.background': alphaOf(fg, 0.16),
    'scrollbarSlider.hoverBackground': alphaOf(fg, 0.24),
    'scrollbarSlider.activeBackground': alphaOf(fg, 0.34),

    'minimap.background': bg,
    'minimap.foregroundOpacity': alphaOf('#000000', 1),
    'minimap.findMatchHighlight': y.number,
    'minimap.selectionHighlight': alphaOf(acc, 0.5),
    'minimap.selectionOccurrenceHighlight': alphaOf(acc, 0.3),
    'minimap.errorHighlight': st.error,
    'minimap.warningHighlight': st.warn,
    'minimap.infoHighlight': st.info,
    'minimap.chatEditHighlight': alphaOf(y.tag, 0.4),
    'minimapSlider.background': alphaOf(fg, 0.1),
    'minimapSlider.hoverBackground': alphaOf(fg, 0.16),
    'minimapSlider.activeBackground': alphaOf(fg, 0.24),
    'minimapGutter.addedBackground': st.added,
    'minimapGutter.modifiedBackground': st.modified,
    'minimapGutter.deletedBackground': st.deleted,

    'quickInput.background': elev,
    'quickInput.foreground': fg,
    'quickInputList.focusBackground': over,
    'quickInputList.focusForeground': fg,
    'quickInputList.focusIconForeground': acc,
    'quickInputTitle.background': over,
    'pickerGroup.border': line,
    'pickerGroup.foreground': acc,
    'keybindingLabel.background': dark ? mixOf(bg, fg, 0.16) : mixOf(bg, fg, 0.10),
    'keybindingLabel.foreground': readable(fg, dark ? mixOf(bg, fg, 0.16) : mixOf(bg, fg, 0.10), 7),
    'keybindingLabel.border': dark ? mixOf(bg, fg, 0.26) : mixOf(bg, fg, 0.20),
    'keybindingLabel.bottomBorder': dark ? mixOf(bg, fg, 0.30) : mixOf(bg, fg, 0.24),
    'keybindingTable.headerBackground': elev,
    'keybindingTable.rowsBackground': alphaOf(fg, 0.03),

    'menu.background': elev,
    'menu.foreground': fg,
    'menu.border': line2,
    'menu.selectionBackground': over,
    'menu.selectionForeground': fg,
    'menu.selectionBorder': '#00000000',
    'menu.separatorBackground': line2,
    'menubar.selectionBackground': alphaOf(fg, 0.1),
    'menubar.selectionForeground': fg,
    'menubar.selectionBorder': '#00000000',

    'banner.background': over,
    'banner.foreground': fg,
    'banner.iconForeground': acc,
    'hover.background': elev,
    'hover.foreground': fg,
    'hover.border': line2,
    'shadow.small': sh(0.10),
    'shadow.medium': sh(0.18),
    'shadow.large': sh(0.28),
  };
}

function integrations(t) {
  const onColor = t.onColor;
  const A = t.ansi;
  const bright = (c) => lighten(c, t.dark ? 0.20 : 0.15);
  const { sh, bg, elev, chrome: ch, over, fg, dim, faint, line, line2, acc, onAcc, st, y, shadow, up, dn, dark } = t;
  return {
    'terminal.background': bg,
    'terminal.foreground': fg,
    'terminal.selectionBackground': t.sel,
    'terminal.inactiveSelectionBackground': t.selSoft,
    'terminal.selectionForeground': fg,
    'terminal.border': line,
    'terminal.dropBackground': alphaOf(acc, 0.16),
    'terminal.tab.activeBorder': acc,
    'terminal.findMatchBackground': alphaOf(y.number, 0.38),
    'terminal.findMatchBorder': y.number,
    'terminal.findMatchHighlightBackground': alphaOf(y.string, 0.24),
    'terminal.hoverHighlightBackground': alphaOf(acc, 0.14),
    'terminalCursor.foreground': acc,
    'terminalCursor.background': bg,
    'terminalCommandDecoration.defaultBackground': faint,
    'terminalCommandDecoration.successBackground': st.ok,
    'terminalCommandDecoration.errorBackground': st.error,
    'terminalOverviewRuler.cursorForeground': acc,
    'terminalOverviewRuler.findMatchForeground': y.number,
    'terminalStickyScroll.background': elev,
    'terminalStickyScrollHover.background': over,
    'terminal.ansiBlack': dark ? mixOf(bg, fg, 0.16) : mixOf(fg, bg, 0.06),
    'terminal.ansiRed': A.red,
    'terminal.ansiGreen': A.green,
    'terminal.ansiYellow': A.yellow,
    'terminal.ansiBlue': A.blue,
    'terminal.ansiMagenta': A.magenta,
    'terminal.ansiCyan': A.cyan,
    'terminal.ansiWhite': dark ? mixOf(fg, bg, 0.2) : mixOf(fg, bg, 0.55),
    'terminal.ansiBrightBlack': dark ? faint : mixOf(fg, bg, 0.38),
    'terminal.ansiBrightRed': bright(A.red),
    'terminal.ansiBrightGreen': bright(A.green),
    'terminal.ansiBrightYellow': bright(A.yellow),
    'terminal.ansiBrightBlue': bright(A.blue),
    'terminal.ansiBrightMagenta': bright(A.magenta),
    'terminal.ansiBrightCyan': bright(A.cyan),
    'terminal.ansiBrightWhite': dark ? fg : mixOf(fg, bg, 0.72),

    'gitDecoration.addedResourceForeground': st.added,
    'gitDecoration.modifiedResourceForeground': st.modified,
    'gitDecoration.deletedResourceForeground': st.deleted,
    'gitDecoration.renamedResourceForeground': y.type,
    'gitDecoration.untrackedResourceForeground': y.type,
    'gitDecoration.ignoredResourceForeground': faint,
    'gitDecoration.conflictingResourceForeground': st.conflict,
    'gitDecoration.stageModifiedResourceForeground': y.keyword,
    'gitDecoration.stageDeletedResourceForeground': st.deleted,
    'gitDecoration.submoduleResourceForeground': y.tag,
    'scmGraph.historyItemHoverLabelForeground': fg,
    'scmGraph.foreground1': y.func,
    'scmGraph.foreground2': y.keyword,
    'scmGraph.foreground3': y.type,
    'scmGraph.foreground4': y.number,
    'scmGraph.foreground5': y.tag,
    'scmGraph.historyItemHoverAdditionsForeground': st.added,
    'scmGraph.historyItemHoverDeletionsForeground': st.deleted,
    'scmGraph.historyItemRefColor': y.func,
    'scmGraph.historyItemRemoteRefColor': y.type,
    'scmGraph.historyItemBaseRefColor': y.keyword,

    'diffEditor.insertedTextBackground': alphaOf(st.added, dark ? 0.12 : 0.14),
    'diffEditor.removedTextBackground': alphaOf(st.deleted, dark ? 0.12 : 0.14),
    'diffEditor.insertedLineBackground': alphaOf(st.added, dark ? 0.07 : 0.08),
    'diffEditor.removedLineBackground': alphaOf(st.deleted, dark ? 0.07 : 0.08),
    'diffEditor.insertedTextBorder': '#00000000',
    'diffEditor.removedTextBorder': '#00000000',
    'diffEditor.border': line,
    'diffEditor.diagonalFill': line2,
    'diffEditor.unchangedRegionBackground': elev,
    'diffEditor.unchangedRegionForeground': dim,
    'diffEditor.unchangedRegionShadow': sh(0.14),
    'diffEditor.unchangedCodeBackground': alphaOf(fg, 0.03),
    'diffEditor.move.border': y.tag,
    'diffEditor.moveActive.border': y.number,
    'diffEditorOverview.insertedForeground': alphaOf(st.added, 0.6),
    'diffEditorOverview.removedForeground': alphaOf(st.deleted, 0.6),
    'diffEditorGutter.insertedLineBackground': alphaOf(st.added, 0.2),
    'diffEditorGutter.removedLineBackground': alphaOf(st.deleted, 0.2),
    'multiDiffEditor.headerBackground': elev,
    'multiDiffEditor.background': bg,
    'multiDiffEditor.border': line,

    'merge.currentHeaderBackground': alphaOf(y.type, 0.3),
    'merge.currentContentBackground': alphaOf(y.type, 0.12),
    'merge.incomingHeaderBackground': alphaOf(y.func, 0.3),
    'merge.incomingContentBackground': alphaOf(y.func, 0.12),
    'merge.commonHeaderBackground': alphaOf(faint, 0.3),
    'merge.commonContentBackground': alphaOf(faint, 0.12),
    'merge.border': '#00000000',
    'mergeEditor.change.background': alphaOf(st.added, 0.12),
    'mergeEditor.change.word.background': alphaOf(st.added, 0.22),
    'mergeEditor.changeBase.background': alphaOf(st.deleted, 0.12),
    'mergeEditor.changeBase.word.background': alphaOf(st.deleted, 0.22),
    'mergeEditor.conflict.unhandledUnfocused.border': alphaOf(st.warn, 0.5),
    'mergeEditor.conflict.unhandledFocused.border': st.warn,
    'mergeEditor.conflict.handledUnfocused.border': alphaOf(st.ok, 0.35),
    'mergeEditor.conflict.handledFocused.border': alphaOf(st.ok, 0.7),
    'mergeEditor.conflict.handled.minimapOverViewRuler': st.ok,
    'mergeEditor.conflict.unhandled.minimapOverViewRuler': st.warn,
    'mergeEditor.conflictingLines.background': alphaOf(st.warn, 0.16),

    'peekView.border': acc,
    'peekViewEditor.background': mixOf(bg, elev, 0.5),
    'peekViewEditor.matchHighlightBackground': alphaOf(y.number, 0.3),
    'peekViewEditor.matchHighlightBorder': '#00000000',
    'peekViewEditorGutter.background': mixOf(bg, elev, 0.5),
    'peekViewEditorStickyScroll.background': mixOf(bg, elev, 0.5),
    'peekViewResult.background': elev,
    'peekViewResult.fileForeground': fg,
    'peekViewResult.lineForeground': dim,
    'peekViewResult.matchHighlightBackground': alphaOf(y.number, 0.3),
    'peekViewResult.selectionBackground': over,
    'peekViewResult.selectionForeground': fg,
    'peekViewTitle.background': elev,
    'peekViewTitleLabel.foreground': fg,
    'peekViewTitleDescription.foreground': dim,

    'notificationCenter.border': line2,
    'notificationCenterHeader.background': over,
    'notificationCenterHeader.foreground': dim,
    'notificationToast.border': line2,
    'notifications.background': elev,
    'notifications.foreground': fg,
    'notifications.border': line,
    'notificationLink.foreground': y.func,
    'notificationsErrorIcon.foreground': st.error,
    'notificationsWarningIcon.foreground': st.warn,
    'notificationsInfoIcon.foreground': st.info,

    'debugToolBar.background': elev,
    'debugToolBar.border': line2,
    'debugIcon.breakpointForeground': st.error,
    'debugIcon.breakpointDisabledForeground': faint,
    'debugIcon.breakpointUnverifiedForeground': faint,
    'debugIcon.breakpointCurrentStackframeForeground': st.warn,
    'debugIcon.breakpointStackframeForeground': dim,
    'debugIcon.startForeground': st.ok,
    'debugIcon.pauseForeground': y.func,
    'debugIcon.stopForeground': st.error,
    'debugIcon.disconnectForeground': st.error,
    'debugIcon.restartForeground': st.ok,
    'debugIcon.stepOverForeground': y.func,
    'debugIcon.stepIntoForeground': y.func,
    'debugIcon.stepOutForeground': y.func,
    'debugIcon.continueForeground': y.func,
    'debugIcon.stepBackForeground': y.func,
    'debugConsole.infoForeground': st.info,
    'debugConsole.warningForeground': st.warn,
    'debugConsole.errorForeground': st.error,
    'debugConsole.sourceForeground': dim,
    'debugConsoleInputIcon.foreground': acc,
    'debugExceptionWidget.background': mixOf(bg, st.error, 0.18),
    'debugExceptionWidget.border': st.error,
    'debugTokenExpression.name': y.func,
    'debugTokenExpression.value': fg,
    'debugTokenExpression.string': y.string,
    'debugTokenExpression.number': y.number,
    'debugTokenExpression.boolean': y.number,
    'debugTokenExpression.error': st.error,
    'debugTokenExpression.type': y.type,
    'debugView.exceptionLabelBackground': st.error,
    'debugView.exceptionLabelForeground': onColor(st.error),
    'debugView.stateLabelBackground': over,
    'debugView.stateLabelForeground': fg,
    'debugView.valueChangedHighlight': alphaOf(y.func, 0.4),
    'editor.stackFrameHighlightBackground': alphaOf(st.warn, 0.16),
    'editor.focusedStackFrameHighlightBackground': alphaOf(st.ok, 0.16),
  };
}

function assistant(t) {
  const { onColor, sh, bg, elev, chrome: ch, over, fg, dim, faint, line, line2, acc, onAcc, st, y, shadow, up, dn, dark } = t;
  const field = dark ? mixOf(bg, fg, 0.08) : '#ffffff';
  return {
    'chat.requestBackground': elev,
    'chat.requestBorder': line2,
    'chat.requestBubbleBackground': over,
    'chat.requestBubbleHoverBackground': mixOf(over, fg, 0.06),
    'chat.requestCodeBorder': line2,
    'chat.list.background': bg,
    'chat.avatarBackground': over,
    'chat.avatarForeground': fg,
    'chat.slashCommandBackground': alphaOf(acc, 0.14),
    'chat.slashCommandForeground': readable(acc, mixOf(ch, acc, 0.16), 5.2),
    'chat.linesAddedForeground': st.added,
    'chat.linesRemovedForeground': st.deleted,
    'chat.editedFileForeground': st.modified,
    'chat.findMatchBackground': alphaOf(y.number, 0.32),
    'chat.findMatchHighlightBackground': alphaOf(y.string, 0.22),
    'chat.thinkingShimmer': alphaOf(acc, 0.55),
    'chat.dictationActiveMicGlow': alphaOf(y.tag, 0.6),
    'chat.inputWorkingBorderColor1': y.keyword,
    'chat.inputWorkingBorderColor2': y.string,
    'chat.inputWorkingBorderColor3': y.tag,
    'chat.checkpointSeparator': line2,
    'chat.attachmentBackground': alphaOf(fg, 0.07),
    'chat.attachmentForeground': dim,

    'inlineChat.background': elev,
    'inlineChat.border': line2,
    'inlineChat.shadow': shadow,
    'inlineChat.regionHighlight': alphaOf(acc, 0.1),
    'inlineChatInput.background': field,
    'inlineChatInput.border': line2,
    'inlineChatInput.focusBorder': acc,
    'inlineChatInput.placeholderForeground': faint,
    'inlineChatDiff.inserted': alphaOf(st.added, 0.12),
    'inlineChatDiff.removed': alphaOf(st.deleted, 0.12),

    'agents.background': bg,
    'agentsPanel.background': elev,
    'agentsPanel.border': line,
    'agentsPanel.foreground': fg,
    'agentsChatInput.background': field,
    'agentsChatInput.foreground': fg,
    'agentsChatInput.border': line2,
    'agentsChatInput.focusBorder': acc,
    'agentsChatInput.placeholderForeground': faint,
    'agentsNewSessionButton.background': acc,
    'agentsNewSessionButton.foreground': onAcc,
    'agentsNewSessionButton.border': '#00000000',
    'agentsNewSessionButton.hoverBackground': up(acc, 0.12),

    'inlineEdit.gutterIndicator.background': alphaOf(acc, 0.2),
    'inlineEdit.gutterIndicator.primaryBorder': acc,
    'inlineEdit.gutterIndicator.primaryForeground': onAcc,
    'inlineEdit.gutterIndicator.primaryBackground': acc,
    'inlineEdit.gutterIndicator.secondaryBorder': line2,
    'inlineEdit.gutterIndicator.secondaryForeground': dim,
    'inlineEdit.gutterIndicator.secondaryBackground': elev,
    'inlineEdit.modifiedBorder': alphaOf(st.modified, 0.6),
    'inlineEdit.modifiedBackground': alphaOf(st.modified, 0.08),
    'inlineEdit.modifiedChangedLineBackground': alphaOf(st.added, 0.1),
    'inlineEdit.modifiedChangedTextBackground': alphaOf(st.added, 0.2),
    'inlineEdit.originalBorder': alphaOf(st.deleted, 0.6),
    'inlineEdit.originalBackground': alphaOf(st.deleted, 0.08),
    'inlineEdit.originalChangedLineBackground': alphaOf(st.deleted, 0.1),
    'inlineEdit.originalChangedTextBackground': alphaOf(st.deleted, 0.2),

    'markdownAlert.note.foreground': st.info,
    'markdownAlert.tip.foreground': st.ok,
    'markdownAlert.important.foreground': y.keyword,
    'markdownAlert.warning.foreground': st.warn,
    'markdownAlert.caution.foreground': st.error,

    'testing.iconFailed': st.error,
    'testing.iconErrored': st.error,
    'testing.iconPassed': st.ok,
    'testing.iconQueued': st.warn,
    'testing.iconSkipped': faint,
    'testing.iconUnset': faint,
    'testing.runAction': st.ok,
    'testing.message.error.decorationForeground': st.error,
    'testing.message.error.lineBackground': alphaOf(st.error, 0.14),
    'testing.message.error.badgeBackground': st.error,
    'testing.message.error.badgeBorder': '#00000000',
    'testing.message.error.badgeForeground': dn(st.error, 0.8),
    'testing.message.info.decorationForeground': st.info,
    'testing.message.info.lineBackground': alphaOf(st.info, 0.12),
    'testing.peekBorder': st.error,
    'testing.peekHeaderBackground': mixOf(bg, st.error, 0.14),
    'testing.messagePeekBorder': st.info,
    'testing.messagePeekHeaderBackground': mixOf(bg, st.info, 0.14),
    'testing.coveredBackground': alphaOf(st.ok, 0.14),
    'testing.coveredBorder': alphaOf(st.ok, 0.4),
    'testing.coveredGutterBackground': alphaOf(st.ok, 0.35),
    'testing.uncoveredBackground': alphaOf(st.error, 0.14),
    'testing.uncoveredBorder': alphaOf(st.error, 0.4),
    'testing.uncoveredGutterBackground': alphaOf(st.error, 0.3),
    'testing.uncoveredBranchBackground': alphaOf(st.warn, 0.22),
    'testing.coverCountBadgeBackground': acc,
    'testing.coverCountBadgeForeground': onAcc,

    'notebook.editorBackground': bg,
    'notebook.cellBorderColor': line,
    'notebook.cellEditorBackground': elev,
    'notebook.cellHoverBackground': alphaOf(fg, 0.03),
    'notebook.cellInsertionIndicator': acc,
    'notebook.cellStatusBarItemHoverBackground': alphaOf(fg, 0.1),
    'notebook.cellToolbarSeparator': line,
    'notebook.focusedCellBackground': alphaOf(acc, 0.05),
    'notebook.focusedCellBorder': acc,
    'notebook.focusedEditorBorder': acc,
    'notebook.inactiveFocusedCellBorder': line2,
    'notebook.inactiveSelectedCellBorder': line2,
    'notebook.outputContainerBackgroundColor': elev,
    'notebook.outputContainerBorderColor': line,
    'notebook.selectedCellBackground': alphaOf(fg, 0.04),
    'notebook.selectedCellBorder': line2,
    'notebook.symbolHighlightBackground': alphaOf(y.type, 0.16),
    'notebookScrollbarSlider.background': alphaOf(fg, 0.16),
    'notebookScrollbarSlider.hoverBackground': alphaOf(fg, 0.24),
    'notebookScrollbarSlider.activeBackground': alphaOf(fg, 0.34),
    'notebookStatusErrorIcon.foreground': st.error,
    'notebookStatusRunningIcon.foreground': y.func,
    'notebookStatusSuccessIcon.foreground': st.ok,
    'notebookEditorOverviewRuler.runningCellForeground': y.func,

    'settings.headerForeground': fg,
    'settings.headerBorder': line,
    'settings.focusedRowBackground': alphaOf(fg, 0.04),
    'settings.focusedRowBorder': acc,
    'settings.rowHoverBackground': alphaOf(fg, 0.03),
    'settings.modifiedItemIndicator': acc,
    'settings.dropdownBackground': field,
    'settings.dropdownForeground': fg,
    'settings.dropdownBorder': line2,
    'settings.dropdownListBorder': line2,
    'settings.checkboxBackground': field,
    'settings.checkboxForeground': readable(acc, field, 5.0),
    'settings.checkboxBorder': line2,
    'settings.textInputBackground': field,
    'settings.textInputForeground': fg,
    'settings.textInputBorder': line2,
    'settings.numberInputBackground': field,
    'settings.numberInputForeground': y.number,
    'settings.numberInputBorder': line2,
    'settings.sashBorder': line2,
    'settings.settingsHeaderHoverForeground': fg,

    'charts.foreground': fg,
    'charts.lines': line2,
    'charts.red': st.error,
    'charts.blue': y.func,
    'charts.yellow': st.warn,
    'charts.orange': y.number,
    'charts.green': st.ok,
    'charts.purple': y.keyword,

    'symbolIcon.arrayForeground': y.number,
    'symbolIcon.booleanForeground': y.number,
    'symbolIcon.classForeground': y.type,
    'symbolIcon.colorForeground': y.tag,
    'symbolIcon.constantForeground': y.number,
    'symbolIcon.constructorForeground': y.type,
    'symbolIcon.enumeratorForeground': y.number,
    'symbolIcon.enumeratorMemberForeground': y.number,
    'symbolIcon.eventForeground': y.tag,
    'symbolIcon.fieldForeground': y.prop,
    'symbolIcon.fileForeground': fg,
    'symbolIcon.folderForeground': dim,
    'symbolIcon.functionForeground': y.func,
    'symbolIcon.interfaceForeground': y.type,
    'symbolIcon.keyForeground': y.prop,
    'symbolIcon.keywordForeground': y.keyword,
    'symbolIcon.methodForeground': y.func,
    'symbolIcon.moduleForeground': y.type,
    'symbolIcon.namespaceForeground': y.type,
    'symbolIcon.nullForeground': y.number,
    'symbolIcon.numberForeground': y.number,
    'symbolIcon.objectForeground': y.type,
    'symbolIcon.operatorForeground': y.op,
    'symbolIcon.packageForeground': y.type,
    'symbolIcon.propertyForeground': y.prop,
    'symbolIcon.referenceForeground': y.func,
    'symbolIcon.snippetForeground': y.string,
    'symbolIcon.stringForeground': y.string,
    'symbolIcon.structForeground': y.type,
    'symbolIcon.textForeground': fg,
    'symbolIcon.typeParameterForeground': y.type,
    'symbolIcon.unitForeground': y.number,
    'symbolIcon.variableForeground': y.variable,

    'welcomePage.background': bg,
    'welcomePage.tileBackground': elev,
    'welcomePage.tileHoverBackground': over,
    'welcomePage.tileBorder': line,
    'welcomePage.progress.background': alphaOf(fg, 0.1),
    'welcomePage.progress.foreground': acc,
    'walkThrough.embeddedEditorBackground': mixOf(bg, elev, 0.5),
    'walkthrough.stepTitle.foreground': fg,

    'ports.iconRunningProcessForeground': st.ok,
    'searchEditor.textInputBorder': line2,
    'searchEditor.findMatchBackground': alphaOf(y.number, 0.24),
    'search.resultsInfoForeground': dim,
    'editorCommentsWidget.resolvedBorder': faint,
    'editorCommentsWidget.unresolvedBorder': st.warn,
    'editorCommentsWidget.rangeBackground': alphaOf(st.warn, 0.08),
    'editorCommentsWidget.rangeActiveBackground': alphaOf(st.warn, 0.14),
    'editorCommentsWidget.replyInputBackground': elev,
    'commentsView.resolvedIcon': faint,
    'commentsView.unresolvedIcon': st.warn,
  };
}

export function buildColors(spec) {
  const t = tokens(spec);
  const all = { ...t.editor, ...chrome(t), ...controls(t), ...integrations(t), ...assistant(t), ...remainder(t), ...tail(t) };
  for (const k of Object.keys(all)) if (all[k] === undefined) delete all[k];
  return all;
}

export { tokens };

function remainder(t) {
  const { onColor, sh, bg, elev, over, fg, dim, faint, line, line2, acc, onAcc, st, y, shadow, up, dn, dark } = t;
  const sym = {
    alias: y.variable, argument: y.param, branch: y.type, command: y.func, file: fg,
    folder: dim, inlineSuggestion: faint, method: y.func, option: y.keyword,
    optionValue: y.string, flag: y.keyword, symbolicLinkFile: y.type,
    symbolicLinkFolder: y.type, scmBranch: y.type, scmRemote: y.func, scmStaged: st.added,
    scmModified: st.modified, scmUntracked: y.type, pullRequest: y.tag,
  };
  const out = {};
  for (const [k, v] of Object.entries(sym)) out[`terminalSymbolIcon.${k}Foreground`] = v;
  return {
    ...out,
    'editor.border': line,
    'editor.compositionBorder': acc,
    'editor.findMatchHighlightBorder': '#00000000',
    'editor.linkedEditingBackground': alphaOf(y.tag, 0.14),
    'editor.snippetTabstopHighlightBackground': alphaOf(acc, 0.16),
    'editor.snippetTabstopHighlightBorder': '#00000000',
    'editor.snippetFinalTabstopHighlightBackground': alphaOf(y.type, 0.16),
    'editor.snippetFinalTabstopHighlightBorder': y.type,
    'editor.placeholder.foreground': faint,
    'editorUnicodeHighlight.background': alphaOf(st.warn, 0.14),
    'editorUnicodeHighlight.border': st.warn,
    'editorGutter.addedSecondaryBackground': alphaOf(st.added, 0.5),
    'editorGutter.deletedSecondaryBackground': alphaOf(st.deleted, 0.5),
    'editorGutter.modifiedSecondaryBackground': alphaOf(st.modified, 0.5),
    'editorGutter.commentDraftGlyphForeground': dim,
    'button.hoverForeground': onAcc,
    'button.secondaryBorder': line2,
    'surface.background': elev,
    'surface.foreground': fg,
    'surface.border': line2,
    'activityErrorBadge.background': st.error,
    'activityErrorBadge.foreground': onColor(st.error),
    'activityWarningBadge.background': st.warn,
    'activityWarningBadge.foreground': onColor(st.warn),
    'agentsBadge.background': acc,
    'agentsBadge.foreground': onAcc,
    'agentsUnreadBadge.background': y.tag,
    'agentsUnreadBadge.foreground': onColor(y.tag),
  };
}

function tail(t) {
  const { onColor, sh, bg, elev, over, fg, dim, faint, line, line2, acc, onAcc, st, y, shadow, up, dn, dark } = t;
  return {
    'actionBar.toggledBackground': alphaOf(acc, 0.2),
    'toolbar.hoverOutline': '#00000000',
    'agentStatusIndicator.background': acc,
    'agentsBottomPanel.border': line,
    'agentsCard.border': line2,
    'agentsGradient.tintColor': alphaOf(acc, 0.28),
    'agentsVoice.speakingForeground': y.tag,
    'browser.border': line2,
    'editor.inlineValuesBackground': alphaOf(y.number, 0.12),
    'editor.inlineValuesForeground': mixOf(y.number, fg, 0.25),
    'editor.rangeHighlightBorder': '#00000000',
    'editor.symbolHighlightBorder': '#00000000',
    'editor.wordHighlightBorder': '#00000000',
    'editor.wordHighlightStrongBorder': '#00000000',
    'editor.wordHighlightTextBorder': '#00000000',
    'editorError.border': '#00000000',
    'editorWarning.border': '#00000000',
    'editorInfo.border': '#00000000',
    'editorHint.border': '#00000000',
    'editorIndentGuide.background': line,
    'editorIndentGuide.activeBackground': mixOf(bg, fg, 0.34),
    'editorMarkerNavigation.background': elev,
    'editorMarkerNavigationError.background': st.error,
    'editorMarkerNavigationWarning.background': st.warn,
    'editorMarkerNavigationInfo.background': st.info,
    'editorPane.background': bg,
    'editorStickyScrollGutter.background': mixOf(bg, elev, 0.5),
    'peekViewEditorStickyScrollGutter.background': mixOf(bg, elev, 0.5),
    'editorSuggestWidget.focusOutline': acc,
    'interactive.result.editor.background.color': elev,
    'interactive.session.foreground': fg,
    'mergeEditor.conflict.input1.background': alphaOf(y.type, 0.16),
    'mergeEditor.conflict.input2.background': alphaOf(y.func, 0.16),
    'outputViewStickyScroll.background': elev,
    'quickInput.border': line2,
    'quickInputList.hoverBackground': alphaOf(fg, 0.06),
    'quickInputList.focusHighlightForeground': y.string,
    'scmGraph.historyItemHoverDefaultLabelBackground': over,
    'scmGraph.historyItemHoverDefaultLabelForeground': fg,
    'scrollbar.background': '#00000000',
    'searchEditor.findMatchBorder': alphaOf(y.number, 0.5),
    'shadow.sm': sh(0.10),
    'shadow.md': sh(0.18),
    'shadow.lg': sh(0.28),
    'shadow.xl': sh(0.38),
    'terminal.initialHintForeground': faint,
    'terminalCommandGuide.foreground': alphaOf(acc, 0.4),
    'terminalStickyScroll.border': line,
    'terminalSymbolIcon.commitForeground': y.number,
    'terminalSymbolIcon.tagForeground': y.tag,
    'terminalSymbolIcon.stashForeground': y.keyword,
    'terminalSymbolIcon.remoteForeground': y.func,
    'terminalSymbolIcon.pullRequestDoneForeground': y.type,
    'terminalSymbolIcon.symbolText': fg,
    'textPreformat.border': line2,
  };
}
