// Colour keys that exist only in editors built on VS Code. Their own builds read them, VS Code
// ignores them, and audit.mjs expects every one of them in every theme.
const GROUPS = [
  { editor: 'Devin',
    why: 'the wash behind text the assistant deletes inline; Devin (formerly Windsurf) defaults it to red at 7% whatever the theme, so it takes the family deleted wash',
    keys: ['diffEditor.windsurfRemovedTextBackground'] },
  { editor: 'Void',
    why: 'the line washes of the inline diff; Void defaults them to a fixed green and a fixed red at 10% whatever the theme, so they take the family diff line washes',
    keys: ['void.greenBG', 'void.redBG'] },
  { editor: 'Kiro',
    why: 'the hotkey badge of the inline diff toolbar; Kiro defaults it to orange with black text whatever the theme, so it takes the family button colours',
    keys: ['inlineDiffToolbar.hotkeyBackground', 'inlineDiffToolbar.hotkeyForeground'] },
  { editor: 'Positron',
    why: 'the walkthrough badge on the activity bar; Positron defaults it to VS Code blue, so it takes the activity bar badge colour',
    keys: ['walkthroughActivityBarBadge.background'] },
  { editor: 'Positron',
    why: 'text selected inside the action bar and dialog inputs; Positron defaults it to VS Code blue with white text, so it takes the button colours',
    keys: ['positronActionBar.textInputSelectionBackground', 'positronActionBar.textInputSelectionForeground',
      'positronModalDialog.textInputSelectionBackground', 'positronModalDialog.textInputSelectionForeground'] },
  { editor: 'Positron',
    why: 'the cell cursor and the selection of the data grid; Positron defaults them to fixed blues, so they take the focus ring and the editor selection',
    keys: ['positronDataGrid.cursorBorder', 'positronDataGrid.selectionBorder', 'positronDataGrid.selectionInnerBorder', 'positronDataGrid.selectionBackground'] },
  { editor: 'Positron',
    why: 'the runtime state icons; Positron defaults them to a fixed blue, green and red, so they take the family info, added and deleted colours',
    keys: ['positronRuntime.stateIconActive', 'positronRuntime.stateIconIdle', 'positronRuntime.stateIconDisconnected'] },
  { editor: 'Positron',
    why: 'inputs, checkboxes, separators and small marks of the Positron panes; Positron defaults them to fixed greys and blues, so they take the matching input, checkbox, border, description and status colours',
    keys: ['positronActionBar.textInputBackground', 'positronActionBar.textInputBorder', 'positronActionBar.separator',
      'positronModalDialog.textInputBackground', 'positronModalDialog.textInputBorder', 'positronModalDialog.separator',
      'positronModalDialog.buttonDestructiveForeground', 'positronCheckbox.background', 'positronCheckbox.border', 'positronCheckbox.foreground',
      'positronConsole.traceBackground', 'positronNotebook.cellFooterForeground',
      'positronDataExplorer.invalidFilterBackground', 'positronSplitterExpandCollapseButton.foreground'] },
  { editor: 'Devin and Antigravity',
    why: 'the washes of the AI edit review; when the theme diff text washes fail the editor\'s own test (Devin weighs them against a grey, Antigravity wants the inserted and removed washes apart in lightness), both fall back to a fixed green and red, so the fallbacks take the family diff text washes',
    keys: ['diffEditor.insertedTextBackgroundFallback', 'diffEditor.removedTextBackgroundFallback'] },
  { editor: 'Antigravity',
    why: 'the variants it tries before falling back; Antigravity darkens and lightens each diff text wash and paints the first pair whose lightness parts them, which turns a family wash grey or white in most themes, so the variants take the family diff text washes themselves',
    keys: ['diffEditor.insertedTextBackgroundDarker', 'diffEditor.insertedTextBackgroundLighter', 'diffEditor.removedTextBackgroundDarker', 'diffEditor.removedTextBackgroundLighter'] },
  { editor: 'Devin',
    why: 'the state of a session in its quick pick; Devin defaults them to fixed orange, green, blue, red and purple that fall under 4.5 on many surfaces, so they take the family status colours and the role nearest purple, read at 4.5',
    keys: ['windsurf.sessionStatus.orange', 'windsurf.sessionStatus.green', 'windsurf.sessionStatus.blue', 'windsurf.sessionStatus.red', 'windsurf.sessionStatus.purple'] },
  { editor: 'Trae',
    why: 'its secondary text: task counters, pane titles, hints, the welcome and watermark lines; Trae defaults it to a fixed grey, under 4.5 on the surfaces of 57 themes, so it takes the family description colour',
    keys: ['icube.colorGrayText', 'icube.colorTextGray', 'icube--text-text-secondary'] },
  { editor: 'Cursor',
    why: 'the border of a worktree tab and the empty editor watermark; Cursor defaults them to the warning colour at 40% and the text at 60%, shown at half opacity, so they take the warning colour at 3.0 and a text colour that reads 3.0 at half',
    keys: ['tab.worktreeBorder', 'editorWatermark.foreground'] },
  { editor: 'Positron',
    why: 'the histograms and the missing values bar of the data explorer; Positron fills them with fixed blues, oranges and greys, near white on a light theme, so they take the family function, number and error colours at 3.0 and the quiet text colours',
    keys: ['positronDataExplorer.sparklineFill', 'positronDataExplorer.sparklineHover', 'positronDataExplorer.sparklineAxis',
      'positronDataExplorer.columnNullPercentGraphBackgroundFill', 'positronDataExplorer.columnNullPercentGraphBackgroundStroke', 'positronDataExplorer.columnNullPercentGraphIndicatorFill'] },
  { editor: 'Positron',
    why: 'a tooltip and the outline of a histogram that Positron 2026.09.1 still registers but no longer paints; set so that a build which paints them keeps the hover widget colours and the histogram outline',
    keys: ['positronToolTip.background', 'positronToolTip.border', 'positronDataExplorer.sparklineStroke'] },
];

export const FORK_KEYS = GROUPS.flatMap((g) => g.keys.map((key) => ({ key, editor: g.editor, why: g.why })));
