export const SLOTS = [
  { name: 'Comments', slot: 'comment', scope: ['comment', 'punctuation.definition.comment', 'string.comment'] },
  { name: 'Comment keyword', slot: 'codetag', scope: ['keyword.codetag', 'comment keyword.other', 'storage.type.class.jsdoc'] },
  { name: 'Identifiers', slot: 'identifier', scope: ['variable', 'variable.other', 'variable.other.readwrite',
    'meta.definition.variable.name', 'variable.other.property', 'variable.other.object.property',
    'meta.object-literal.key', 'support.type.property-name', 'variable.other.member', 'entity.name.label'] },
  { name: 'Calls', slot: 'call', scope: ['meta.function-call.generic', 'variable.function'] },
  { name: 'Parameters', slot: 'parameter', scope: ['variable.parameter', 'meta.parameter', 'variable.other.jsdoc'] },
  { name: 'Function definitions', slot: 'definition', scope: ['entity.name.function', 'meta.definition.function',
    'meta.definition.method', 'entity.name.method', 'entity.name.function.decorator'] },
  { name: 'Type definitions', slot: 'typedef', scope: ['entity.name.type', 'entity.name.class', 'entity.name.namespace',
    'entity.name.type.interface', 'entity.name.type.enum', 'entity.name.type.alias', 'meta.type.declaration',
    'entity.name.scope-resolution'] },
  { name: 'Types in annotations', slot: 'type', scope: ['support.type.primitive', 'keyword.type', 'storage.type.primitive'] },
  { name: 'Builtins', slot: 'builtin', scope: ['support.function', 'support.class', 'support.type', 'support.type.builtin',
    'support.variable', 'support.constant', 'support.module', 'meta.require', 'variable.language',
    'variable.language.this', 'variable.language.super', 'keyword.other.this'] },
  { name: 'Constants', slot: 'frozen', scope: ['variable.other.constant', 'variable.other.enummember',
    'constant.other.caps', 'entity.name.constant', 'constant.language', 'constant.language.boolean',
    'constant.language.null', 'constant.language.undefined'] },
  { name: 'Strings', slot: 'string', scope: ['string', 'string.quoted', 'string.template', 'punctuation.definition.string'] },
  { name: 'Numbers and units', slot: 'number', scope: ['constant.numeric', 'keyword.other.unit', 'constant.character',
    'constant.character.escape'] },
  { name: 'Regular expressions', slot: 'regexp', scope: ['string.regexp', 'constant.regexp',
    'constant.other.character-class.regexp'] },
  { name: 'Rust lifetimes', slot: 'attribute', scope: ['entity.name.type.lifetime',
    'punctuation.definition.lifetime', 'storage.modifier.lifetime'] },
  { name: 'GraphQL declarations', slot: 'keyword', scope: ['entity.name.fragment', 'entity.scalar',
    'keyword.fragment', 'keyword.interface', 'keyword.enum', 'keyword.input', 'keyword.implements',
    'keyword.directive', 'keyword.on', 'keyword.union', 'keyword.scalar', 'keyword.type'] },
  { name: 'GraphQL and data keys', slot: 'identifier', scope: ['constant.object.key', 'scalar.field'] },
  { name: 'HCL and Terraform', slot: 'call', scope: ['storage.type.function.hcl', 'support.function.builtin.hcl',
    'support.function.namespaced.hcl', 'support.function.builtin.terraform'] },
  { name: 'Packages and modules', slot: 'typedef', scope: ['entity.name.package', 'entity.name.namespace.package'] },
  { name: 'Error types', slot: 'frozen', scope: ['entity.name.error', 'entity.name.type.error'] },
  { name: 'Module file operators', slot: 'operator', scope: ['operator.go.mod', 'keyword.operator.go.mod'] },
  { name: 'Regexp operators', slot: 'regexpop', scope: ['keyword.operator.or.regexp', 'keyword.control.anchor.regexp',
    'keyword.operator.quantifier.regexp'] },
  { name: 'Keywords', slot: 'keyword', scope: ['keyword', 'keyword.control', 'keyword.other', 'storage', 'storage.type',
    'storage.modifier', 'keyword.operator.expression', 'keyword.operator.new', 'keyword.operator.delete',
    'keyword.operator.logical.python'] },
  { name: 'Effectful keywords', slot: 'effect', scope: ['keyword.control.flow.await', 'storage.modifier.async',
    'keyword.control.trycatch', 'keyword.control.exception', 'keyword.other.throw', 'keyword.control.flow.return',
    'storage.modifier.async.js', 'keyword.control.flow.yield', 'keyword.operator.new'] },
  { name: 'Import and export', slot: 'import', scope: ['keyword.control.import', 'keyword.control.export',
    'keyword.control.from', 'keyword.control.default', 'keyword.control.as'] },
  { name: 'Arrow functions', slot: 'arrow', scope: ['storage.type.function.arrow', 'keyword.operator.arrow',
    'storage.type.function.lambda'] },
  { name: 'Operators and punctuation', slot: 'operator', scope: ['keyword.operator', 'punctuation',
    'punctuation.separator', 'punctuation.terminator', 'meta.brace', 'punctuation.accessor',
    'punctuation.definition.template-expression', 'punctuation.section.embedded', 'meta.embedded'] },
  { name: 'Tags', slot: 'tag', scope: ['entity.name.tag', 'punctuation.definition.tag', 'meta.tag'] },
  { name: 'Component tags', slot: 'component', scope: ['support.class.component', 'entity.name.tag.jsx-component',
    'entity.name.tag.namespace'] },
  { name: 'Attributes', slot: 'attribute', scope: ['entity.other.attribute-name', 'meta.attribute',
    'entity.other.attribute-name.html', 'entity.other.inherited-class'] },
  { name: 'Decorators', slot: 'decorator', scope: ['meta.decorator', 'punctuation.decorator'] },
  { name: 'CSS selectors', slot: 'cssSelector', scope: ['entity.name.tag.css', 'entity.other.attribute-name.class.css',
    'entity.other.attribute-name.id.css', 'entity.other.attribute-name.pseudo-class.css',
    'entity.other.attribute-name.pseudo-element.css'] },
  { name: 'CSS properties', slot: 'cssProp', scope: ['support.type.property-name.css', 'meta.property-name.css'] },
  { name: 'CSS values', slot: 'cssValue', scope: ['support.constant.property-value.css', 'support.constant.color',
    'constant.other.color'] },
  { name: 'JSON and YAML keys', slot: 'dataKey', scope: ['support.type.property-name.json',
    'meta.structure.dictionary.json', 'entity.name.tag.yaml', 'support.type.property-name.yaml'] },
  { name: 'JSON values', slot: 'dataValue', scope: ['meta.structure.dictionary.value.json'] },
  { name: 'Markup heading', slot: 'heading', scope: ['markup.heading', 'entity.name.section'] },
  { name: 'Markup link', slot: 'link', scope: ['markup.underline.link', 'string.other.link'] },
  { name: 'Markup emphasis', slot: 'emphasis', scope: ['markup.italic'] },
  { name: 'Markup strong', slot: 'strong', scope: ['markup.bold'] },
  { name: 'Markup quote', slot: 'quote', scope: ['markup.quote', 'punctuation.definition.quote.begin', 'blockquote'] },
  { name: 'Markup code', slot: 'code', scope: ['markup.inline.raw', 'markup.fenced_code', 'markup.raw'] },
  { name: 'Markup list', slot: 'list', scope: ['markup.list', 'punctuation.definition.list.begin', 'punctuation.definition.list.end'] },
  { name: 'Diff inserted', slot: 'added', scope: ['markup.inserted', 'meta.diff.header.to-file'] },
  { name: 'Diff deleted', slot: 'deleted', scope: ['markup.deleted', 'meta.diff.header.from-file'] },
  { name: 'Diff header', slot: 'diffHeader', scope: ['meta.diff.header', 'meta.diff.range'] },
  { name: 'Shell variables', slot: 'shellVar', scope: ['variable.other.normal.shell', 'punctuation.definition.variable.shell'] },
  { name: 'Heading levels', slot: 'heading', scope: ['heading', 'heading.1.markdown', 'heading.2.markdown',
    'heading.3.markdown', 'heading.4.markdown', 'heading.5.markdown', 'heading.6.markdown',
    'entity.name.section.group-title'] },
  { name: 'Lists and tables', slot: 'list', scope: ['markup.list.unnumbered', 'markup.list.numbered', 'markup.table',
    'markup.underline'] },
  { name: 'Log errors', slot: 'invalid', scope: ['log.error', 'log.exception', 'log.exceptiontype'] },
  { name: 'Log warnings', slot: 'deleted', scope: ['log.warning'] },
  { name: 'Log info and dates', slot: 'operator', scope: ['log.info', 'log.date', 'log.verbose', 'log.debug'] },
  { name: 'Log values', slot: 'string', scope: ['log.constant', 'log.string'] },
  { name: 'Operators by name', slot: 'operator', scope: ['entity.name.operator', 'entity.name.operator.type',
    'entity.name.operator.custom-literal', 'punctuation.vararg-ellipses'] },
  { name: 'Preprocessor macros', slot: 'macro', scope: ['entity.name.other.preprocessor',
    'entity.name.other.preprocessor.macro', 'entity.name.other.preprocessor.macro.include'] },
  { name: 'Labels and native attributes', slot: 'attribute', scope: ['entity.name.label', 'entity.name.label.call',
    'support.other.attribute', 'entity.other.attribute'] },
  { name: 'Declared names', slot: 'identifier', scope: ['entity.name.variable', 'entity.name.variable.local',
    'entity.name.variable.property', 'entity.name.variable.field', 'entity.name.variable.parameter'] },
  { name: 'Doc comment tags', slot: 'codetag', scope: ['constant.other.description.jsdoc',
    'constant.other.email.link.underline.jsdoc', 'entity.name.type.instance.jsdoc'] },
  { name: 'Regexp character classes', slot: 'regexp', scope: ['constant.other.character-class',
    'constant.other.character-class.set', 'constant.other.character-class.range'] },
  { name: 'Math constants', slot: 'number', scope: ['constant.other.general.math', 'constant.other.math',
    'line.separator.math'] },
  { name: 'Lisp keywords and globals', slot: 'keyword', scope: ['constant.keyword', 'entity.global'] },
  { name: 'Generic constants', slot: 'frozen', scope: ['constant.other', 'constant.sha', 'constant.global',
    'constant.other.symbol', 'constant.other.option'] },
  { name: 'Generic raw markup', slot: 'code', scope: ['markup.raw', 'markup.raw.texttt', 'markup.raw.verbatim',
    'markup.raw.verb', 'markup.raw.yaml.front-matter'] },
  { name: 'Attribute values', slot: 'cssValue', scope: ['entity.other.attribute-value', 'property.value',
    'constant.other.inline-data'] },
  { name: 'References and footnotes', slot: 'link', scope: ['constant.other.reference.citation',
    'constant.other.reference.label', 'entity.name.footnote'] },
  { name: 'Character literals', slot: 'number', scope: ['char', 'constant.character.character-class', 'constant.character.control'] },
  { name: 'Anonymous and inline functions', slot: 'call', scope: ['function.anonymous', 'name.generic.filter',
    'args.mixin'] },
  { name: 'Inline tags', slot: 'tag', scope: ['tag.inline', 'tag.case.control.flow', 'inline'] },
  { name: 'Snippet placeholders', slot: 'operator', scope: ['custom.punctuation', 'custom.variable',
    'punctuation.section.insertion'] },
  { name: 'Expression groups', slot: 'operator', scope: ['expression.group'] },
  { name: 'CSS and Less extras', slot: 'cssProp', scope: ['entity.other.keyframe-offset',
    'entity.other.counter-style-name', 'entity.other.counter-name', 'entity.other.namespace-prefix',
    'entity.name.namespace-prefix', 'support.keyword.repetitions', 'support.other.variable',
    'support.unicode-range', 'constant.codepoint-range'] },
  { name: 'Enums and module names', slot: 'frozen', scope: ['constant.enum', 'constant.variable',
    'entity.name.import', 'entity.name.module', 'support.other.namespace', 'support.namespace',
    'entity.other.alias'] },
  { name: 'Language protocols and attributes', slot: 'attribute', scope: ['support.other.protocol',
    'support.attribute', 'support.other.php', 'entity.scope', 'entity.name.pragma.name',
    'constant.name.attribute.tag'] },
  { name: 'Goto labels and document markers', slot: 'operator', scope: ['entity.name.goto-label',
    'entity.other.document.begin', 'entity.other.document.end'] },
  { name: 'Regexp anchors and groups', slot: 'regexpop', scope: ['support.other.match',
    'support.other.parenthesis.regexp', 'support.other.escape.special.regexp'] },
  { name: 'Inline and block math', slot: 'number', scope: ['markup.math.block', 'markup.math.inline'] },
  { name: 'Documentation strings', slot: 'string', scope: ['constant.string.documentation'] },
  { name: 'Invalid', slot: 'invalid', scope: ['invalid', 'invalid.illegal'] },
  { name: 'Deprecated, strikethrough', slot: 'deprecated', scope: ['invalid.deprecated'] },
];

export function buildFrom(paint) {
  const out = [];
  for (const s of SLOTS) {
    const v = paint(s.slot);
    if (!v) continue;
    const settings = typeof v === 'string' ? { foreground: v } : v;
    if (!settings.foreground) continue;
    out.push({ name: s.name, scope: s.scope, settings });
  }
  return out;
}

export const styled = (foreground, fontStyle) => (fontStyle ? { foreground, fontStyle } : { foreground });
